# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       quillimagefilter
Summary:    Qt based library for individual image processing operations
Version:    1.111202.0
Release:    0
Group:      System/Libraries
License:    LGPLv2
URL:        http://maemo.gitorious.org/meego-image-editor/quillimagefilters
Source0:    meego-image-editor-%{name}s-%{version}.tar.gz
Source100:  quillimagefilter.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(quillmetadata)
BuildRequires:  pkgconfig(QtCore)
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  libjpeg-devel


%description
A Qt based library which contains individual image loading, processing
and saving operations optimized for mobile devices. Operations are
used by libquill but can be also used directly if the high-level
engine framework of libquill is not desired.



%package tests
Summary:    Qt based image processing library - unit tests
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   testrunner-lite
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description tests
A Qt based library which contains individual image loading, processing
and saving operations optimized for mobile devices. Operations are
used by libquill but can be also used directly if the high-level
engine framework of libquill is not desired.

This package includes the unit tests.


%package benchmark
Summary:    Qt based image processing library - benchmark
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description benchmark
A Qt based library which contains individual image loading, processing
and saving operations optimized for mobile devices. Operations are
used by libquill but can be also used directly if the high-level
engine framework of libquill is not desired.

This package includes the benchmark.


%package devel
Summary:    Qt based image processing library - development headers
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
A Qt based library which contains individual image loading, processing
and saving operations optimized for mobile devices. Operations are
used by libquill but can be also used directly if the high-level
engine framework of libquill is not desired.

This package includes the development headers.



%prep
%setup -q -n meego-image-editor-%{name}s

# >> setup
# << setup

%build
# >> build pre
unset LD_AS_NEEDED
qmake COV_OPTION=off
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig



%post tests -p /sbin/ldconfig

%postun tests -p /sbin/ldconfig







%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/libquillimagefilter.so.*
%{_libdir}/qt4/plugins/quillimagefilters/*.so
# << files


%files tests
%defattr(-,root,root,-)
# >> files tests
%{_libdir}/libut_unittests.so*
%{_libdir}/quillimagefilter-tests/*
%{_datadir}/quillimagefilter-tests/*
# << files tests

%files benchmark
%defattr(-,root,root,-)
# >> files benchmark
%{_libdir}/quillimagefilter-benchmark/
%{_datadir}/quillimagefilter-benchmark/
# << files benchmark

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/*
%{_libdir}/libquillimagefilter*.so
%{_libdir}/pkgconfig/quillimagefilter.pc
%{_datadir}/qt4/mkspecs/features/quillimagefilter.prf
# << files devel

